# Coding tasks

## Python

In [30]:
#basic program
name=input("Enter your name:")
age=int(input("Enter your age:"))
print(f"My name is {name} and I am {age} years old.")

Enter your name: Alice
Enter your age: 10

My name is Alice and I am 10 years old.

In [4]:
#even or odd
num=int(input("Enter a number:"))
if num%2==0:
    print("Even number.")
else:
    print("Odd number")

Enter a number: 45

Odd number

In [6]:
#List operations
numbers=[10,20,30,40,50]
print("sum:",sum(numbers))
print("Max:",max(numbers))
print("Min:",min(numbers))

sum: 150
Max: 50
Min: 10

In [8]:
#function example
def square(num):
    return num*num
print(square(10))

100

In [9]:
#loop task
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9

In [10]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9

In [18]:
#Dynamic Typing
#Write a program that: * Assigns an integer value to a variable * Reassigns a string value to the same variable * Prints the value and its type at each step
x=10
print(x,type(x))
x="Welcome"
print(x,type(x))

10 <class 'int'>
Welcome <class 'str'>

In [21]:
#mutable vs immutable datatypes
#Write a program that: * Modifies a list * Attempts to modify a tuple
my_list=[10,20,30]
my_list[1]=22
print(my_list)
my_tuple=(100,200,300)
my_tuple[1]=222
print(my_tuple)

[10, 22, 30]

TypeError: 'tuple' object does not support item assignment

In [26]:
#local and global variables
#Write a program that * uses a global variable * uses a local variable inside a function
x=100
def demo():
    y=50
    print("global x is printing inside demo function - ",x)
    print("global x and local y printing inside demo function - ",x,y)
demo()
print("global x printing in main - ",x)
print("local y of 'demo' function printing outside demo - ",y)

global x is printing inside demo function -  100
global x and local y printing inside demo function -  100 50
global x printing in main -  100

NameError: name 'y' is not defined

In [33]:
#'return' statement in a function
#write a function that * takes two numbers *returns their sum
def sum(a,b):
    return a+b
s=sum(4,5)
print("sum :",s)

sum : 9

In [1]:
#list comprehension
#write a program that * create a list of squares from 1 to 10
squares=[i*i for i in range(1,11)]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [2]:
#break,continue and pass
#write a program that * Demonstrate break,continue and pass
for i in range(1,11):
    if i==3:
        continue
    if i==5:
        break
    if i==7:
        pass
    print(i)

1
2
4

In [5]:
#recursion
#Writw a recursive function that : *finds the factorial of a number
def factorial(n):
    if n==0:
        return 1
    return n*factorial(n-1)
print(factorial(5))

120

In [7]:
#lambda function
#Write a lambda function that : *returns the square of a number
square=lambda x:x*x
print(square(5))

25

In [8]:
#is vs ==
#write a program that : *Compares two lists using == and is
a=[1,2,3]
b=[1,2,3]
print(a==b)
print(a is b)

True
False

In [31]:
#Docstrings
#Write a function that * uses a docstring
def greet():
    """This function prints a greeting message"""
    print("Hello Python")
greet()
print(greet.__doc__)

Hello Python
This function prints a greeting message

Functions in Python are objects and Python stores extra metadata using special attributes called dunder attributes (double underscore).
Examples:
__doc__ documentation string
__name__ function name
__defaults__  default arguments
Formal Definition:
__doc__ is a built-in attribute that stores the docstring of a function, class, module, or method.
The docstring is the string written immediately below the function definition

## NumPy

In [7]:
import numpy as np

In [13]:
#create arrays
a=np.array([10,20,30])
print(a)

[10 20 30]

In [16]:
#array operations
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
print(a+b)
print(a*b)

[11 22 33 44]
[ 10  40  90 160]

In [20]:
#zeroes and ones
print(np.zeros((2,3)))
print(np.ones((4,5)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

In [28]:
#mean,max,min
data=np.array([10,20,30,40,50])
print(data.mean())
print(data.max())
print(data.min())
print("........")
print(np.mean(data))
print(np.max(data))
print(np.min(data))

30.0
50
10
........
30.0
50
10

## Pandas

In [3]:
import pandas as pd

In [4]:
#create DataFrame
data={
    "Name":["Alice","Bob","Charlie"],
    "Age":[21,22,23],
    "Marks":[45,34,49]
}
df=pd.DataFrame(data)
print(df)

      Name  Age  Marks
0    Alice   21     45
1      Bob   22     34
2  Charlie   23     49

In [5]:
#read CSV
df=pd.read_csv("sample.csv")
print(df)

   product  sales  profit
0        A    448      76
1        B    370      83
2        C    970      19
3        D    560      30
4        E    688      73
..     ...    ...     ...
95       A    183      36
96       B    759      76
97       C    237      91
98       D    306      71
99       E    839      69

[100 rows x 3 columns]

In [6]:
df=pd.read_csv("students_performance.csv")
print(df.head(5))

   student_id  hours_studied  previous_score extracurricular  \
0           1            5.5              85             Yes
1           2            4.2              79             Yes
2           3            5.8              69              No
3           4            7.5              60             Yes
4           5            4.0              76             Yes

   extracurricular_hours  sleep_hours  practice_questions  performance_index
0                    1.2          8.5                  26               40.9
1                    2.0          7.5                  22               55.5
2                    0.2          5.8                  79               39.3
3                    2.7          6.6                  24               42.0
4                    3.9          6.3                  22               42.8

In [7]:
df.head(5)

,student_id,hours_studied,previous_score,extracurricular,extracurricular_hours,sleep_hours,practice_questions,performance_index
0,1,5.5,85,Yes,1.2,8.5,26,40.9
1,2,4.2,79,Yes,2.0,7.5,22,55.5
2,3,5.8,69,No,0.2,5.8,79,39.3
3,4,7.5,60,Yes,2.7,6.6,24,42.0
4,5,4.0,76,Yes,3.9,6.3,22,42.8

In [8]:
#basic operations
print(df["sleep_hours"].mean())

6.927899999999999

In [9]:
print(df["previous_score"]<60)

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997     True
998    False
999     True
Name: previous_score, Length: 1000, dtype: bool

In [14]:
#filtering

print(df[df["previous_score"]<60])

     student_id  hours_studied  previous_score extracurricular  \
29           30            3.9              56              No
31           32            8.2              48             Yes
36           37            4.9              53             Yes
37           38            0.6              50             Yes
47           48            6.6              49             Yes
..          ...            ...             ...             ...
978         979            1.3              59             Yes
980         981            6.1              56             Yes
981         982            5.4              51             Yes
997         998            5.8              57             Yes
999        1000            5.6              59              No

     extracurricular_hours  sleep_hours  practice_questions  performance_index
29                     0.5          6.1                  13               29.3
31                     2.9          9.0                  34               35.8
36                     4.8          5.7                  17               30.6
37                     5.8          5.2                  40                6.4
47                     6.7          5.9                  47               23.7
..                     ...          ...                 ...                ...
978                    2.3          7.4                   8               20.0
980                    2.0          8.6                  21               27.8
981                    2.7          6.0                  39               25.0
997                    3.4          7.7                  57               42.8
999                    0.4          7.1                  27               36.1

[210 rows x 8 columns]

In [31]:
#Learn Pandas step by step using real datasets created with NumPy
#Dataset 1: Titanic like Passenger Dataset using NumPy
np.random.seed(1)#random.seed() controls the starting point of randomness.same seed-same sequence for ever.
rows=200
df=pd.DataFrame({
    "PassengerId":np.arange(1,rows+1),
    "Name":np.random.choice(["Alice","BOB","John","Maria"],rows),
    "Age":np.random.choice(np.append(np.random.randint(1,80,180),[np.nan]*20),rows),#180 random integers and 20 null values created and appended to get "Age".But as choice function applied ,we cant be sure 20 % data will be null.
    "Sex":np.random.choice(["Male","Female","Trans"],rows),
    "Pclass":np.random.choice([1,2,3],rows),
    "Fare":np.round((np.random.uniform(10,500,rows)),2)#200 random floating point numbers are created and fractional part is rounded to 2
})
df

     PassengerId   Name   Age     Sex  Pclass    Fare
0              1    BOB  40.0   Trans       3  218.53
1              2  Maria   NaN    Male       1  393.27
2              3  Alice  75.0   Trans       2   37.51
3              4  Alice  63.0  Female       1  419.28
4              5  Maria  39.0   Trans       1  104.20
..           ...    ...   ...     ...     ...     ...
195          196   John  40.0    Male       2  319.51
196          197  Maria  33.0   Trans       3  356.59
197          198    BOB  75.0   Trans       3  310.66
198          199    BOB   NaN   Trans       2  327.67
199          200   John  33.0    Male       2   93.27

[200 rows x 6 columns]

In [56]:
#here "Age"is float type.we can change to "Int64"-can hold int + NaN.if normal "int" is used,NaN data forces type to "float"
df["Age"]=df["Age"].astype("Int64")

# other better option is,for "Age",create a series.ten add to dataframe
np.random.seed(1)
rows=200
ages=np.append(random.randint(1,80,180),[np.nan]*20)
np.random.shuffle(ages)
df=pd.DataFrame({
    "PasengerId":np.arange(1,rows+1),
    "Name":np.random.choice(["Paul","Johnson","Maria","Zara"],rows),
    "Age":pd.Series(ages).astype("Int64"),
    "Sex":np.random.choice(["Male","Female","Trans"]rows),
    "Pclass":np.random.choice([1,2,3])
    "Fare":np.round(np.random.uniform(10,500,rows),2)
})

In [28]:
import numpy as np
import pandas as pd
np.random.seed(1)
rows=200
ages=np.append(np.random.randint(1,80,180),[np.nan]*20)
np.random.shuffle(ages)
df_corrected=pd.DataFrame({
    "PasengerId":np.arange(1,rows+1),
    "Name":np.random.choice(["Paul","Johnson","Maria","Zara"],rows),
    "Age":pd.Series(ages).astype("Int64"),
    "Sex":np.random.choice(["Male","Female","Trans"],rows),
    "Pclass":np.random.choice([1,2,3]),
    "Fare":np.round(np.random.uniform(10,500,rows),2)
})
df_corrected

     PasengerId     Name   Age     Sex  Pclass    Fare
0             1    Maria    78  Female       1  498.41
1             2     Paul  <NA>   Trans       1  410.25
2             3    Maria     6    Male       1  301.24
3             4     Zara    28    Male       1  488.23
4             5     Paul    46  Female       1  451.77
..          ...      ...   ...     ...     ...     ...
195         196     Zara    61    Male       1  439.91
196         197     Paul     8    Male       1  229.37
197         198    Maria    41    Male       1  394.38
198         199    Maria     9   Trans       1  233.91
199         200  Johnson    26   Trans       1  331.55

[200 rows x 6 columns]

In [29]:
df.isnull().sum()

student_id               0
hours_studied            0
previous_score           0
extracurricular          0
extracurricular_hours    0
sleep_hours              0
practice_questions       0
performance_index        0
dtype: int64

In [30]:
#View data
df.head()
df.tail()
df.sample(3)

,student_id,hours_studied,previous_score,extracurricular,extracurricular_hours,sleep_hours,practice_questions,performance_index
689,690,5.4,65,Yes,4.1,8.4,24,42.4
363,364,5.3,56,Yes,0.8,7.7,61,40.8
962,963,4.9,74,Yes,3.9,4.5,48,28.5

In [14]:
#Inspect structure
df.shape

(1000, 8)

In [15]:
df.columns

Index(['student_id', 'hours_studied', 'previous_score', 'extracurricular',
       'extracurricular_hours', 'sleep_hours', 'practice_questions',
       'performance_index'],
      dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   student_id             1000 non-null   int64
 1   hours_studied          1000 non-null   float64
 2   previous_score         1000 non-null   int64
 3   extracurricular        1000 non-null   str
 4   extracurricular_hours  1000 non-null   float64
 5   sleep_hours            1000 non-null   float64
 6   practice_questions     1000 non-null   int64
 7   performance_index      1000 non-null   float64
dtypes: float64(4), int64(3), str(1)
memory usage: 65.5 KB

In [17]:
df.describe()

,student_id,hours_studied,previous_score,extracurricular_hours,sleep_hours,practice_questions,performance_index
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.0000,1000.00000
mean,500.500000,4.544100,68.835000,2.906500,6.927900,41.5890,40.19880
std,288.819436,1.943734,11.951343,2.208757,1.182163,28.9254,11.01319
min,1.000000,0.000000,33.000000,0.000000,3.200000,6.0000,0.00000
25%,250.750000,3.200000,61.000000,1.200000,6.200000,24.0000,33.20000
50%,500.500000,4.550000,69.000000,2.400000,7.000000,34.0000,40.50000
75%,750.250000,5.800000,77.000000,3.900000,7.800000,51.0000,47.10000
max,1000.000000,12.000000,100.000000,10.000000,10.000000,227.0000,69.70000

In [18]:
#Handle Missing data
df.isnull().sum()

student_id               0
hours_studied            0
previous_score           0
extracurricular          0
extracurricular_hours    0
sleep_hours              0
practice_questions       0
performance_index        0
dtype: int64

In [19]:

df.isnull().sum()

student_id               0
hours_studied            0
previous_score           0
extracurricular          0
extracurricular_hours    0
sleep_hours              0
practice_questions       0
performance_index        0
dtype: int64

In [32]:
#filtering rows
df_age_morethan_30=df[df["Age"]>30]
df_age_morethan_30

     PassengerId   Name   Age     Sex  Pclass    Fare
0              1    BOB  40.0   Trans       3  218.53
2              3  Alice  75.0   Trans       2   37.51
3              4  Alice  63.0  Female       1  419.28
4              5  Maria  39.0   Trans       1  104.20
6              7  Maria  55.0  Female       2  157.04
..           ...    ...   ...     ...     ...     ...
194          195  Alice  53.0    Male       2   38.25
195          196   John  40.0    Male       2  319.51
196          197  Maria  33.0   Trans       3  356.59
197          198    BOB  75.0   Trans       3  310.66
199          200   John  33.0    Male       2   93.27

[122 rows x 6 columns]

In [33]:
df[df["Sex"]=="Female"]

     PassengerId   Name   Age     Sex  Pclass    Fare
3              4  Alice  63.0  Female       1  419.28
6              7  Maria  55.0  Female       2  157.04
10            11  Alice  77.0  Female       2  270.04
15            16  Alice  17.0  Female       2  258.88
25            26  Alice  27.0  Female       3  395.69
..           ...    ...   ...     ...     ...     ...
176          177   John  79.0  Female       3  121.82
178          179    BOB  10.0  Female       2  214.19
186          187  Alice   NaN  Female       2  352.66
188          189   John  40.0  Female       1  134.16
191          192   John  78.0  Female       1  218.08

[64 rows x 6 columns]

In [34]:
#Grouping & Aggregation
# //value_counts 
df.groupby('Pclass')["Fare"].mean()

Pclass
1    262.445714
2    279.171711
3    230.427647
Name: Fare, dtype: float64

# DATASET 2: Student Performance Dataset

## Purpose: Sorting, value counts, apply, conditional columns

In [48]:
np.random.seed(2)
rows=150
age=np.append(np.random.randint(18,30,int(rows*.8)),[np.nan]*int(rows*.2))
np.random.shuffle(age)
df=pd.DataFrame({
    "Student_id":np.arange(1,rows+1),
    "Age":pd.Series(age,dtype="Int64"),
    "Gender":np.random.choice(["Male","Female","Trans"],rows),
    "Course":np.random.choice(["B.Sc-CS","BCA","BA-English","MCA"],rows),
    "Marks":np.random.randint(35,100,rows)
})
df

     Student_id   Age  Gender      Course  Marks
0             1    26   Trans         MCA     43
1             2    26   Trans         MCA     88
2             3  <NA>   Trans         MCA     53
3             4    29  Female     B.Sc-CS     73
4             5    29  Female     B.Sc-CS     40
..          ...   ...     ...         ...    ...
145         146    23    Male  BA-English     84
146         147    28  Female         BCA     61
147         148    26    Male         BCA     81
148         149    28   Trans         MCA     58
149         150    23   Trans         BCA     60

[150 rows x 5 columns]

In [49]:
#sorting data
df.sort_values(by="Marks",ascending=False)

     Student_id   Age  Gender      Course  Marks
43           44    20  Female         BCA     99
38           39    23  Female  BA-English     99
117         118    23    Male         MCA     99
135         136    28    Male  BA-English     99
61           62    28   Trans         MCA     98
..          ...   ...     ...         ...    ...
56           57    20    Male     B.Sc-CS     37
42           43    23   Trans         MCA     37
130         131  <NA>   Trans         BCA     37
58           59  <NA>   Trans  BA-English     37
136         137    19   Trans  BA-English     36

[150 rows x 5 columns]

In [50]:
#value counts
df["Gender"].value_counts()

Gender
Trans     64
Female    44
Male      42
Name: count, dtype: int64

In [52]:
#apply function
df["Result"]=df["Marks"].apply(lambda x :"Pass" if x>=50 else "fail")
df.head()

   Student_id   Age  Gender   Course  Marks Result
0           1    26   Trans      MCA     43   fail
1           2    26   Trans      MCA     88   Pass
2           3  <NA>   Trans      MCA     53   Pass
3           4    29  Female  B.Sc-CS     73   Pass
4           5    29  Female  B.Sc-CS     40   fail

In [53]:
#grouping
df.groupby("Course")["Marks"].mean()

Course
B.Sc-CS       70.157895
BA-English    66.875000
BCA           65.131579
MCA           65.558824
Name: Marks, dtype: float64

# DATASET 3: Employee Dataset

## Purpose: Rename, drop, mapping, aggregation

In [16]:
import numpy as np
import pandas as pd
np.random.seed(3)
rows=120
df=pd.DataFrame({
    "EmpId":np.arange(1,rows+1),
    "Dept":np.random.choice(["HR","IT","Sales"]),
    "Salary":np.random.randint(30000,150000,rows),
    "Gender":np.random.choice(["Male","female","Trans"],rows),
    "Age":np.random.randint(18,65,rows)
})
df

     EmpId   Dept  Salary  Gender  Age
0        1  Sales   97224  female   63
1        2  Sales  107049  female   25
2        3  Sales   89011    Male   51
3        4  Sales   78056    Male   52
4        5  Sales  121080    Male   39
..     ...    ...     ...     ...  ...
115    116  Sales  113768  female   19
116    117  Sales   70552  female   56
117    118  Sales  104023    Male   36
118    119  Sales   36429    Male   47
119    120  Sales   97248   Trans   39

[120 rows x 5 columns]

In [3]:
#view data
df.head()
df.tail()
df.sample(5)

     EmpId   Dept  Salary  Gender  Age
115    116  Sales  113768  female   19
27      28  Sales   38127    Male   54
70      71  Sales   38021    Male   60
79      80  Sales   91328  female   22
16      17  Sales   89872  female   62

In [4]:
#inspect structure
df.shape

(120, 5)

In [5]:
df.columns

Index(['EmpId', 'Dept', 'Salary', 'Gender', 'Age'], dtype='str')

In [6]:
df.describe

<bound method NDFrame.describe of      EmpId   Dept  Salary  Gender  Age
0        1  Sales   97224  female   63
1        2  Sales  107049  female   25
2        3  Sales   89011    Male   51
3        4  Sales   78056    Male   52
4        5  Sales  121080    Male   39
..     ...    ...     ...     ...  ...
115    116  Sales  113768  female   19
116    117  Sales   70552  female   56
117    118  Sales  104023    Male   36
118    119  Sales   36429    Male   47
119    120  Sales   97248   Trans   39

[120 rows x 5 columns]>

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   EmpId   120 non-null    int32
 1   Dept    120 non-null    str
 2   Salary  120 non-null    int32
 3   Gender  120 non-null    str
 4   Age     120 non-null    int32
dtypes: int32(3), str(2)
memory usage: 4.6 KB

In [8]:
#handling missing values
df.isnull().sum()

EmpId     0
Dept      0
Salary    0
Gender    0
Age       0
dtype: int64

In [14]:
df["Age"]=df["Age"].fillna(df["Age"].mean())
df

     EmpId   Dept  Salary  Gender  Age
0        1  Sales   97224  female   63
1        2  Sales  107049  female   25
2        3  Sales   89011    Male   51
3        4  Sales   78056    Male   52
4        5  Sales  121080    Male   39
..     ...    ...     ...     ...  ...
115    116  Sales  113768  female   19
116    117  Sales   70552  female   56
117    118  Sales  104023    Male   36
118    119  Sales   36429    Male   47
119    120  Sales   97248   Trans   39

[120 rows x 5 columns]

In [ ]:
# Use specific placeholders based on data types
df_filled = df.fillna({
    'Age': 25,
    'City': 'Unknown',
    'Salary': df['Salary'].mean()  # Fill using calculation
})

In [ ]:
# Fill a column using its mean value
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Fill a column using its median value
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

# Fill a categorical column using its most frequent value (mode)
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [20]:
#rename and drop
df.rename(columns={"Dept":"Department"},inplace=True)
df.drop("Age",axis=1,inplace=True)
df

     EmpId Department  Salary  Gender
0        1      Sales   97224  female
1        2      Sales  107049  female
2        3      Sales   89011    Male
3        4      Sales   78056    Male
4        5      Sales  121080    Male
..     ...        ...     ...     ...
115    116      Sales  113768  female
116    117      Sales   70552  female
117    118      Sales  104023    Male
118    119      Sales   36429    Male
119    120      Sales   97248   Trans

[120 rows x 4 columns]